// action-types.js
const actionTypes = {
  // Xrefs
  GET_USER: 'GET_USER',
  GET_USER_FAIL: 'GET_USER_FAIL',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  // Locale
  GET_LOCALE_MESSAGES: 'GET_LOCALE_MESSAGES',
  GET_LOCALE_MESSAGES_SUCCESS: 'GET_LOCALE_MESSAGES_SUCCESS'
};

export {actionTypes};
